---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: deploy-overlays-dev # The full path in the repository to the path
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./deploy/overlays/dev # This is the current working directory followed
                   # by the path you specified to gitops run
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
